name: SEMamba
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.12
  - cudatoolkit=11.8
  - pytorch=2.2
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - cuda-nvcc=11.8
  - gcc_windows-64=11
  - gxx_windows-64=11
  - pip
  - pip:
    - causal-conv1d>=1.2.0
    - mamba_ssm
    - einops
